backend/apps/base/urls.py
from django.conf.urls import url, include
from django.contrib.auth.views import logout, LoginView
from django.contrib.auth.decorators import login_required
from django.views.generic.base import RedirectView

from backend.apps.base.views import *

urlpatterns = [
    url(r'^login/$', LoginView.as_view(template_name='base/login.html') , name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^$', login_required(home), name='home'),
]

backend/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('backend.apps.base.urls', namespace='base')),
]

backend/apps/base/models/base_model.py
import json

from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

from service import Service


class BaseRequest(models.Model):
    VALID_STATUSES = [
        ('accepted', 'accepted'),
        ('queued', 'queued'),
        ('sending', 'sending'),
        ('sent', 'sent'),
        ('receiving', 'receiving'),
        ('received', 'received'),
        ('delivered', 'delivered'),
        ('undelivered', 'undelivered'),
        ('failed', 'failed'),
    ]

    QUEUES = [
        (1, 'priority'),
        (2, 'other'),
        (3, 'sms_box'),
    ]

    VALID_INFRASTRUCTURES = [
        (1, 'twilio'),
        (2, 'smsbox1'),
        (3, 'smsbox2')
    ]
    user = models.ForeignKey(User)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    recipient_phone_number = models.CharField(validators=[phone_regex], max_length=15) # validators should be a list
    country = models.CharField(max_length=64, blank=True, null=True)
    msg = models.CharField(max_length=1600)
    msg_sid = models.CharField(max_length=64, blank=True, null=True)
    timestamp_send = models.DateTimeField(auto_now_add=True)
    timestamp_confirmation = models.DateTimeField(blank=True, null=True)
    # queue = models.CharField(choices=QUEUES, max_length=32, blank=True)
    # general status and message set by twilio using the callback url
    status = models.CharField(max_length=32, choices=VALID_STATUSES, blank=True, null=True)
    service_response = models.CharField(max_length=1024, blank=True, null=True)
    # the service used to send the sms/voice
    service = models.ForeignKey(Service, default=None, related_name='service')
    infrastructure_used = models.CharField(max_length=32, choices=VALID_INFRASTRUCTURES, blank=True, null=True)

    class Meta:
        abstract = True
        permissions = (
            ("view", "Can view data"),
            )

    def __str__(self):
        return '{} - {}'.format(self.recipient_phone_number, self.msg)

    def __unicode__(self):
        return '{} - {}'.format(self.recipient_phone_number, self.msg)

backend/apps/base/views/base_view.py
import math

# rest framework related imports
from rest_framework.authentication import SessionAuthentication, BasicAuthentication
from rest_framework.permissions import IsAuthenticated, BasePermission
from rest_framework.views import APIView
from rest_framework.parsers import JSONParser
from rest_framework_xml.parsers import XMLParser
from rest_framework.renderers import JSONRenderer
from rest_framework_xml.renderers import XMLRenderer
from rest_framework.exceptions import AuthenticationFailed
from oauth2_provider.ext.rest_framework import OAuth2Authentication
from django_auth_ldap.backend import LDAPBackend


from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.conf import settings


class PaginationMixIn():
    def paginate(self, objects):
        page_size = int(self.request.query_params.get('page_size', settings.DEFAULT_PAGE_SIZE))
        if page_size != -1:
            total_objects = len(objects)
            paginator = Paginator(objects, page_size)
            page = int(self.request.query_params.get('page', 1))
            try:
                objects = paginator.page(page)
            except PageNotAnInteger:
                objects = paginator.page(1)
            except EmptyPage:
                objects = paginator.page(paginator.num_pages)

            response = {}
            response['objects'] = objects.object_list
            response['page_number'] = page
            response['total_pages'] = int(math.ceil(total_objects / float(page_size)))
            response['page_size'] = page_size
        else:
            response = {'objects': objects}
        return response


class ApiBaseView(APIView):
    authentication_classes = (BasicAuthentication, OAuth2Authentication, SessionAuthentication, LDAPBackend)
    # add permission class to check the priority(if a service is available for a certain user) and the maximum amount
    permission_classes = (IsAuthenticated,)
    parser_classes = (JSONParser, XMLParser)
    renderer_classes = (JSONRenderer, XMLRenderer)

backend/apps/base/views/home.py
from django.shortcuts import render

def home(request):
    return render(request, 'base/home.html')

backend/templates/base/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
{% load util_filters %}

<head>
    <meta charset="UTF-8">
    {% block title %}
    <title></title>
    {% endblock title %}
    {% block css %}
    <link rel="icon" type="image/gif" href="{% static 'base/images/favicon.gif' %}"/>
    <link rel="stylesheet" href="{% static 'base/css/semantic.min.css' %}" type="text/css"/>
    <link rel="stylesheet" type="text/css" href="{% static 'base/css/daterangepicker.min.css' %}">
    <!-- <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet"> -->

    <style>
        html {
            height: 100%;
            width: 100%;
        }

        body {
            height: 100%;
            width: 100%;
            /*font-family: 'Varela Round', sans-serif;*/
            background: -webkit-radial-gradient(circle, rgba(237, 240, 242, 0.2), rgba(237, 240, 242, 1));
        }

        body > .ui.menu {
            border-radius: 0px;
        }

        .full-height {
            height: 100%;
        }

        #cgk-logo {
            background: white;
            padding: 0px 0px 0px 10px;
            border-radius: 0px;
            width: 145px;
        }

        #mon-content {
            padding: 0px 50px;
        }

        .ui.horizontal.divider:after, .ui.horizontal.divider:before {
            /* Hack for chrome version */
            top: initial!important;
        }
    </style>
    {% endblock css %}
</head>
<body>
    <div class="ui menu">
        <div id="cgk-logo" class="header item">
            <a class="ui logo icon image" href="/">
                <img src="{% static 'base/images/cgk-logo.png' %}">
            </a>
        </div>

        <div class="ui dropdown simple item" tabindex="0">
            Home<i class="dropdown icon"></i>
            <div class="menu" tabindex="-1">
                <a class="item" href="{% url 'base:home' %}">Home</a>
            </div>
        </div>


        <div class="right menu">
            <a class="item">Settings</a>
            <a id="logout" href="{% url 'base:logout' %}" class="item">Logout</a>
        </div>

    </div>

    <div class="ui main container fluid" style="height:92%">
        <div id="wrapper" class="full-height">
            <div id="mon-content" class="ui container fluid full-height">
                {% block maincontent %}
                {% endblock %}
            </div>
        </div>
    </div>
    {% block footer %}
    {% endblock footer %}
    {% block js %}
        <script src="{% static 'base/js/jquery-3.1.0.min.js' %}"></script>
        <script src="{% webpack_static 'dist/vendor.dist.js' %}"></script>
        <script src="{% webpack_static 'dist/base.dist.js' %}"></script>
    {% endblock %}
</body>
</html>

backend/templates/base/home.html
{% extends 'base/base.html' %}
{% block title %}<title>MON starter project </title>{% endblock title %}
{% block css %}
    {{ block.super }}
    <style>
        .temp {
            display: table;
            width: 100%;
        }

        .temp > h1 {
            display: table-cell;
            text-align: center;
            vertical-align: middle;
        }
    </style>
{% endblock css %}
{% block maincontent %}
<div class="temp full-height">
    <h1 id="root">Hello!</h1>
</div>
{% endblock maincontent %}

backend/templates/base/login.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'base/css/semantic.min.css' %}" type="text/css"/>
    <style type="text/css">
        body {
            background-color: #DADADA;
        }
        body > .grid {
            height: 100%;
        }
        .image {
            margin-top: -100px;
        }
        .column {
            max-width: 450px;
        }
    </style>
</head>
<body>
    <div class="ui middle aligned center aligned grid">
        <div class="column">
            <form class="ui large form" method="post" action=".">
            {% csrf_token %}
                <div class="ui stacked segment">
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="user icon"></i>
                            <input id="username" type="text" name="username" placeholder="username">
                        </div>
                    </div>
                    <div class="field">
                        <div class="ui left icon input">
                            <i class="lock icon"></i>
                            <input id="password" name="password" type="password" autocomplete="off" placeholder="password">
                        </div>
                    </div>
                    <div id="submit" class="ui fluid large submit button">Login</div>
                </div>
                <input type="hidden" name="next" value="{{ next }}" />
                <div class="ui error message">
                </div>
            </form>
        </div>
    </div>
    <script src="{% static 'base/js/jquery-3.1.0.min.js' %}"></script>
    <script src="{% static 'base/js/semantic.min.js' %}"></script>
    <script>
        $(document).ready(function() {
            $('.ui.form').form({
                fields: {
                    username: {
                        identifier  : 'username',
                        rules: [{
                            type   : 'empty',
                            prompt : 'Please enter your username'
                        }]
                    },
                    password: {
                        identifier  : 'password',
                        rules: [{
                            type   : 'empty',
                            prompt : 'Please enter your password'
                        }]
                    }
                }
            });
        });
        $('#username').focus();
        {% if form.errors %}
        $('.ui.form').form('add errors', ['Incorrect username/password combination']);
        {% endif %}
    </script>
</body>
</html>